name: proyecto_colon_unfv
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.4.0

  shared_preferences: ^2.2.2

  image_picker: ^1.0.7

  provider: ^6.1.1

  cupertino_icons: ^1.0.8

  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
